global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'packet_sniffer'
    static_configs:
      - targets: ['app:8000']  # Если приложение экспонирует метрики